<?php  $productos = array(
		1 => array( 'id' => '1','nombre' => 'The Godfather', 'genero' => 'Crimen, Drama','anio' => '1972',
		'director' => 'Francis Ford Coppola', 'actores' => 'Marlon Brando, Al Pacino, James Caan',
		'duracion' => '2h 55min', 'rating' => '9.2', 'clasificacion' => '+18',
		'descripcion' => 'Don Vito Corleone es el jefe de una de las cinco familias que ejercen el mando de la Cosa Nostra en Nueva York en los años 40. Don Corleone tiene cuatro hijos; una chica, Connie, y tres varones, Santino, o Sonny, como le gusta que le llamen, Michael y Freddie, al que envían exiliado a Las Vegas, dada su incapacidad para asumir puestos de mando en la Familia. Cuando otro capo, Sollozzo, al rechazar el Padrino intervenir en el negocio de estupefacientes, intenta asesinar a éste, empieza una cruenta lucha de violentos episodios entre los distintos grupos.',
		'imagen' => 'the_godfather.jpg','activo' => true, 'precio' => '200', 'categorias' => array(16,18)),
		2 => array( 'id' => '2','nombre' => 'The Godfather II', 'genero' => 'Crimen, Drama','anio' => '1974',
		'director' => 'Francis Ford Coppola', 'actores' => 'Al Pacino, Robert De Niro, Robert Duvall',
		'duracion' => '3h 22min', 'rating' => '9.0', 'clasificacion' => '+18',
		'descripcion' => 'Michael Corleone lidera el imperio criminal de su padre, mientras que se recuerda el ascenso al poder del joven Vito.',
		'imagen' => 'the_godfather2.jpg','activo' => true, 'precio' => '200', 'categorias' => array (18,16)),
		3 => array( 'id' => '3','nombre' => 'Centigrade', 'genero' => 'Suspenso, Drama','anio' => '2020'
        , 'director' => 'Brendan Walsh', 'actores' => 'Mavis Simpson-Ernst, Vincent Piazza, Genesis Rodriguez',
        'duracion' => '1h 38min', 'rating' => '4.2', 'clasificacion' => '+16'
        , 'descripcion' => 'Un matrimonio se queda atrapado en su vehículo congelado después de una tormenta y tiene que luchar para sobrevivir.'
        , 'imagen' => 'centigrade.jpg','activo' => true, 'precio' => '150', 'categorias' => array (18,23)),
        4 => array( 'id' => '4','nombre' => 'Harpoon', 'genero' => 'Comedia, Suspenso','anio' => '2019'
        , 'director' => 'Rob Grant', 'actores' => 'Munro Chambers, Christopher Gray, Emily Tyra',
        'duracion' => '1h 23min', 'rating' => '6.0', 'clasificacion' => '+18'
        , 'descripcion' => 'Tres amigos se quedan en un yate a la deriva en medio del océano. Sin escapatoria y luchando por sobrevivir, con mucho alcohol pero poca comida y agua, con el tiempo los tres jóvenes se dejarán llevar por la rivalidad, la envidia y por la tensión sexual.'
        , 'imagen' => 'harpoon.jpg','activo' => true, 'precio' => '200', 'categorias' => array (15,23)),
        5 => array( 'id' => '5','nombre' => 'Doctor Sleep', 'genero' => 'Drama, Suspenso, Dantasia','anio' => '2019'
        , 'director' => 'Mike Flanagan', 'actores' => 'Ewan McGregor, Rebecca Ferguson, Kyliegh Curran',
        'duracion' => '2h 32min', 'rating' => '7.4', 'clasificacion' => '+16'
        , 'descripcion' => 'Dan, alcohólico y traumatizado por lo que le pasó siendo un niño en el hotel Overlook, conoce a Abra, una adolescente que posee el mismo don que él. Dan tratará de salvar a Abra de un grupo de siniestros personajes que ansían la inmortalidad y aspiran alcanzarla alimentándose de los poderes psíquicos de gente como ellos.'
        , 'imagen' => 'doctor_sleep.jpg','activo' => true, 'precio' => '150', 'categorias' => array (18,19,23)),
        6 => array( 'id' => '6','nombre' => 'Dreamcatcher', 'genero' => 'Drama, Suspenso, Ciencia Ficcion','anio' => '2003'
        , 'director' => 'Lawrence Kasdan', 'actores' => 'Morgan Freeman, Thomas Jane, Jason Lee',
        'duracion' => '2h 16min', 'rating' => '5.5', 'clasificacion' => '+18'
        , 'descripcion' => 'Basada en la obra de Stephen King. Cuatro amigos unidos por telepatía enfrentan a alienígenas en los bosques de Maine.'
        , 'imagen' => 'dreamcatcher.jpg','activo' => true, 'precio' => '200', 'categorias' => array (14,18,23)),
        7 => array( 'id' => '7','nombre' => 'Arrival', 'genero' => 'Drama, Suspenso, Ciencia Ficcion','anio' => '2016'
        , 'director' => 'Denis Villeneuve', 'actores' => 'Amy Adams, Jeremy Renner, Forest Whitaker',
        'duracion' => '1h 56min', 'rating' => '7.9', 'clasificacion' => '+13'
        , 'descripcion' => 'El gobierno contrata a la prestigiosa lingüista Louise Banks para que se comunique con unos alienígenas que han llegado a la Tierra. Conforme ella aprende su idioma, va experimentando regresiones muy intensas que desvelan la verdadera misión que les ha llevado hasta nuestro planeta.'
		, 'imagen' => 'arrival.jpg','activo' => true, 'precio' => '120', 'categorias' => array (14,18,23)),
		8 => array( 'id' => '8','nombre' => 'The New Mutants', 'genero' => 'Accion, Suspenso, Ciencia Ficcion','anio' => '2020'
		, 'director' => 'Josh Boone', 'actores' => 'Maisie Williams, Anya Taylor-Joy, Charlie Heaton',
		'duracion' => '1h 34min', 'rating' => '5.5', 'clasificacion' => '+13'
		, 'descripcion' => 'Cinco jóvenes mutantes que acaban de descubrir sus habilidades, son encerrados en unas instalaciones secretas contra su voluntad y luchan por escapar de su pasado y salvarse a sí mismos.'
		, 'imagen' => 'the_new_mutants.jpg','activo' => true, 'precio' => '120', 'categorias' => array (12,14,23)),
		9 => array( 'id' => '9','nombre' => 'Interstellar', 'genero' => 'Aventura, Drama, Ciencia Ficcion','anio' => '2014'
		, 'director' => 'Christopher Nolan', 'actores' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
		'duracion' => '2h 49min', 'rating' => '8.6', 'clasificacion' => '+13'
		, 'descripcion' => 'Al ver que la vida en la Tierra está llegando a su fin, un grupo de exploradores dirigidos por el piloto Cooper (McConaughey) y la científica Amelia (Hathaway) emprende una misión que puede ser la más importante de la historia de la humanidad: viajar más allá de nuestra galaxia para descubrir algún planeta en otra que pueda garantizar el futuro de la raza humana.'
		, 'imagen' => 'interstellar.jpg','activo' => true, 'precio' => '120', 'categorias' => array (13,14,18)),
		10 => array( 'id' => '10','nombre' => 'Inception', 'genero' => 'Accion, Aventura, Ciencia Ficcion','anio' => '2010'
		, 'director' => 'Christopher Nolan', 'actores' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
		'duracion' => '2h 28min', 'rating' => '8.8', 'clasificacion' => '+13'
		, 'descripcion' => 'Dom Cobb es un ladrón con una extraña habilidad para entrar a los sueños de la gente y robarles los secretos de sus subconscientes. Su habilidad lo ha vuelto muy popular en el mundo del espionaje corporativo, pero ha tenido un gran costo en la gente que ama. Cobb obtiene la oportunidad de redimirse cuando recibe una tarea imposible: plantar una idea en la mente de una persona. Si tiene éxito, será el crimen perfecto, pero un enemigo se anticipa a sus movimientos.'
		, 'imagen' => 'inception.jpg','activo' => true, 'precio' => '120', 'categorias' => array (12,13,14)),
		11 => array( 'id' => '11','nombre' => 'Proyecto Power', 'genero' => 'Accion, Ciencia Ficcion','anio' => '2020'
		, 'director' => 'Henry Joost, Ariel Schulman', 'actores' => 'Jamie Foxx, Joseph Gordon-Levitt, Dominique Fishback',
		'duracion' => '1h 53min', 'rating' => '6.0', 'clasificacion' => '+16'
		, 'descripcion' => 'Un exsoldado se une a un policía para encontrar la fuente detrás de una píldora peligrosa que proporciona superpoderes temporales.'
		, 'imagen' => 'proyecto_power.jpg','activo' => true, 'precio' => '150', 'categorias' => array (12,14)),
		12 => array( 'id' => '12','nombre' => 'Tenet', 'genero' => 'Accion, Ciencia Ficcion','anio' => '2020'
		, 'director' => 'Christopher Nolan', 'actores' => 'John David Washington, Robert Pattinson, Elizabeth Debicki',
		'duracion' => '2h 30min', 'rating' => '7.8', 'clasificacion' => '+13'
		, 'descripcion' => 'Una acción épica que gira en torno al espionaje internacional, los viajes en el tiempo y la evolución, en la que un agente secreto debe prevenir la Tercera Guerra Mundial.'
		, 'imagen' => 'tenet.jpg','activo' => true, 'precio' => '120', 'categorias' => array (12,14)),
		13 => array( 'id' => '13','nombre' => 'Harry Potter and the Sorcerers Stone', 'genero' => 'Aventura, Fantasia','anio' => '2001'
		, 'director' => 'Chris Columbus', 'actores' => 'Daniel Radcliffe, Rupert Grint, Richard Harris',
		'duracion' => '2h 32min', 'rating' => '7.6', 'clasificacion' => 'ATP'
		, 'descripcion' => 'El día de su cumpleaños, Harry Potter descubre que es hijo de dos conocidos hechiceros, de los que ha heredado poderes mágicos. Debe asistir a una famosa escuela de magia y hechicería, donde entabla una amistad con dos jóvenes que se convertirán en sus compañeros de aventura. Durante su primer año en Hogwarts, descubre que un malévolo y poderoso mago llamado Voldemort está en busca de una piedra filosofal que alarga la vida de quien la posee.'
		, 'imagen' => 'harry_potter_and_the_sorcerers_stone.jpg','activo' => true, 'precio' => '100', 'categorias' => array (13,19)),
		14 => array( 'id' => '14','nombre' => 'Pirates of the Caribbean: The Curse of the Black Pearl', 'genero' => 'Accion, Aventura, Fantasia','anio' => '2003'
		, 'director' => 'Gore Verbinski', 'actores' => 'Johnny Depp, Geoffrey Rush, Orlando Bloom',
		'duracion' => '2h 23min', 'rating' => '8.0', 'clasificacion' => 'ATP'
		, 'descripcion' => 'El capitán Barbossa le roba el barco al pirata Jack Sparrow y secuestra a Elizabeth, amiga de Will Turner. Barbossa y su tripulación son víctimas de un conjuro que los condena a vivir eternamente y a transformarse cada noche en esqueletos vivientes.'
		, 'imagen' => 'pirates_of_the_caribbean_the_curse_of_the_black_pearl.jpg','activo' => true, 'precio' => '100', 'categorias' => array (12,13,19)),
		15 => array( 'id' => '15','nombre' => 'Justice League', 'genero' => 'Accion, Aventura, Fantasia','anio' => '2017'
		, 'director' => 'Zack Snyder', 'actores' => 'Ben Affleck, Gal Gadot, Jason Momoa',
		'duracion' => '2h', 'rating' => '6.3', 'clasificacion' => 'ATP'
		, 'descripcion' => 'Gracias a su renovada fe en la humanidad e inspirado por el acto de altruísmo de Superman, Bruce Wayne pide ayuda a su nueva aliada, Diana Prince, para enfrentar a un enemigo aún más peligroso.'
		, 'imagen' => 'justice_league.jpg','activo' => true, 'precio' => '100', 'categorias' => array (12,13,19)),
		16 => array( 'id' => '16','nombre' => 'The Lord of the Rings: The Fellowship of the Ring', 'genero' => 'Accion, Aventura, Fantasia, Drama','anio' => '2001'
		, 'director' => 'Peter Jackson', 'actores' => 'Elijah Wood, Ian McKellen, Orlando Bloom',
		'duracion' => '2h 58min', 'rating' => '8.8', 'clasificacion' => '+13'
		, 'descripcion' => 'Frodo Bolsón es un hobbit al que su tío Bilbo hace portador del poderoso Anillo Único, capaz de otorgar un poder ilimitado al que la posea, con la finalidad de destruirlo. Sin embargo, fuerzas malignas muy poderosas quieren arrebatárselo.'
		, 'imagen' => 'the_lord_of_the_rings_the_fellowship_of_the_ring.jpg','activo' => true, 'precio' => '120', 'categorias' => array (12,13,19,18)),
		17 => array( 'id' => '17','nombre' => 'Avatar', 'genero' => 'Accion, Aventura, Fantasia','anio' => '2009'
		, 'director' => 'James Cameron', 'actores' => 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
		'duracion' => '2h 42min', 'rating' => '7.8', 'clasificacion' => 'ATP'
		, 'descripcion' => 'En un exuberante planeta llamado Pandora viven los Navi, seres que aparentan ser primitivos pero que en realidad son muy evolucionados. Debido a que el ambiente de Pandora es venenoso, los híbridos humanos/Navi, llamados Avatares, están relacionados con las mentes humanas, lo que les permite moverse libremente por Pandora. Jake Sully, un exinfante de marina paralítico se transforma a través de un Avatar, y se enamora de una mujer Navi.'
		, 'imagen' => 'avatar.jpg','activo' => true, 'precio' => '100', 'categorias' => array (12,13,19)),
		18 => array( 'id' => '18',
		'nombre' => 'Scary Movie', 
		'genero' => 'Comedia, Terror',
		'anio' => '2000',
		'director' => 'Keenen Ivory Wayans', 
		'actores' => 'Anna Faris, Jon Abrahams, Carmen Electra.',
		'duracion' => '1h 28 min', 
		'rating' => '5.2', 
		'clasificacion' => '+16',
		'descripcion' => 'Una bella estudiante muere asesinada. Un grupo de desorientados adolescentes descubre que entre ellos hay un asesino. La heroína Cyndi Campbell y su grupo de despistados amigos se verán aterrorizados por un singular psicópata enmascarado que pretende vengarse de ellos, después de que lo atropellaran por accidente el pasado Halloween.',
		'imagen' => 'scary_movie.jpg','activo' => true, 'precio' => '150', 'categorias' => array (15,24)),
		19 => array( 'id' => '19',
		'nombre' => 'The Hangover', 
		'genero' => 'Comedia',
		'anio' => '2009',
		'director' => 'Todd Phillips', 
		'actores' => 'Bradley Cooper, Ed Helms, Zach Galifianakis, Justin Bartha',
		'duracion' => '1h 40 min', 
		'rating' => '6.6', 
		'clasificacion' => '+16',
		'descripcion' => 'Historia de una desmadrada despedida de soltero en la que el novio y tres amigos se montan una gran juerga en Las Vegas. Como era de esperar, a la mañana siguiente tienen una resaca tan monumental que no pueden recordar nada de lo ocurrido la noche anterior. Lo más extraordinario es que el novio ha desaparecido y en la suite del hotel se encuentran un tigre y un bebé.',
		'imagen' => 'the_hangover.jpg','activo' => true, 'precio' => '150', 'categorias' => array (15)),
		20 => array( 'id' => '20',
		'nombre' => 'Grown Ups', 
		'genero' => 'Comedia',
		'anio' => '2010',
		'director' => 'Dennis Dugan', 
		'actores' => 'Adam Sandler, Kevin James, Chris Rock ',
		'duracion' => '1h 57 min', 
		'rating' => '4.9', 
		'clasificacion' => '+13',
		'descripcion' => 'Después de treinta años, cinco amigos vuelven a verse para asistir al funeral de su entrenador de baloncesto de la infancia. Con sus esposas e hijos a cuestas, deciden pasar el fin de semana del 4 de julio en una casa cerca de un lago, en la que muchos años antes habían celebrado la conquista de un campeonato. Curiosamente, esos días de convivencia les harán comprender que, a pesar de que ya son personas adultas, en realidad no han madurado.',
		'imagen' => 'grown_ups.jpg','activo' => true, 'precio' => '120', 'categorias' => array (15)),
		21 => array( 'id' => '21',
		'nombre' => 'Mr. Beans Holiday', 
		'genero' => 'Comedia',
		'anio' => '2007',
		'director' => 'Steve Bendelack', 
		'actores' => 'Rowan Atkinson, Emma de Caunes, Willem Dafoe. ',
		'duracion' => '1h 50 min', 
		'rating' => '4.9', 
		'clasificacion' => 'ATP',
		'descripcion' => 'Mister Bean decide irse de vacaciones al sur de Francia y convierte su viaje de Londres a la Costa Azul en un auténtico caos: por dondequiera que pasa provoca verdaderos estragos.',
		'imagen' => 'mr_bean_s_holiday.jpg','activo' => true, 'precio' => '100', 'categorias' => array (15)),
		22 => array( 'id' => '22',
		'nombre' => 'Me, Myself & Irene', 
		'genero' => 'Comedia',
		'anio' => '2000',
		'director' => 'Peter Farrelly', 
		'actores' => 'Jim Carrey, Renée Zellweger, Anthony Anderson.',
		'duracion' => '1h 57 min', 
		'rating' => '5.5', 
		'clasificacion' => '+16',
		'descripcion' => 'Charlie es un inocente y amable policía de Rhode Island que es todo un caballero, además de un abnegado padre soltero de tres hijos de color que su esposa tuvo tras una aventura. Pero un día Charlie, conocido por su buen carácter, no soporta más que le tomen por blando y sufre de repente un trastorno de personalidad, convirtiéndose en alguien completamente distinto, en el que sale a relucir su hiperagresividad.',
		'imagen' => 'me_myself_irene.jpg','activo' => true, 'precio' => '150', 'categorias' => array (15)),
		23 => array( 'id' => '23',
		'nombre' => 'Indiana Jones: Raiders of the Lost Ark', 
		'genero' => 'Aventura, Acción',
		'anio' => '1981',
		'director' => 'Steven Spielberg', 
		'actores' => 'Harrison Ford, Karen Allen, Paul Freeman',
		'duracion' => '1h 55 min', 
		'rating' => '7.8', 
		'clasificacion' => '+13',
		'descripcion' => 'Año 1936. Indiana Jones es un profesor de arqueología, dispuesto a correr peligrosas aventuras con tal de conseguir valiosas reliquias históricas. Después de una infructuosa misión en Sudamérica, el gobierno estadounidense le encarga la búsqueda del Arca de la Alianza, donde se conservan las Tablas de la Ley que Dios entregó a Moisés. Según la leyenda, quien las posea tendrá un poder absoluto, razón por la cual también la buscan los nazis.',
		'imagen' => 'indiana_jones_raiders_of_the_lost_ark.jpg','activo' => true, 'precio' => '120', 'categorias' => array (12,13)),
		24 => array( 'id' => '24',
		'nombre' => 'The Mummy', 
		'genero' => 'Aventura, Acción, Fantasia',
		'anio' => '1999',
		'director' => 'Stephen Sommers', 
		'actores' => 'Rachel Weisz, John Hannah, Arnold Vosloo',
		'duracion' => '2h 05 min', 
		'rating' => '6.2', 
		'clasificacion' => '+13',
		'descripcion' => 'Durante una batalla en Egipto, el legionario Rick OConnell y un compañero descubren las ruinas de Hamunaptra, la ciudad de los muertos. Algún tiempo después vuelven al mismo lugar con una egiptóloga y su hermano. Allí coinciden con un grupo de estadounidenses, deseosos de correr aventuras, que acabarán provocando la resurrección de la momia de un diabólico sacerdote egipcio que intenta desesperadamente recuperar a su amada.',
		'imagen' => 'the_mummy.jpg','activo' => true, 'precio' => '120', 'categorias' => array (12,13,19)),
		25 => array( 'id' => '25',
		'nombre' => 'Life of Pi', 
		'genero' => 'Aventura, Drama',
		'anio' => '2012',
		'director' => 'Ang Lee', 
		'actores' => 'Suraj Sharma, Irrfan Khan, Rafe Spall',
		'duracion' => '2h 07 min', 
		'rating' => '7.1', 
		'clasificacion' => '+13',
		'descripcion' => 'Tras un naufragio en medio del océano Pacífico, el joven hindú Pi, hijo de un guarda de zoo que viajaba de la India a Canadá, se encuentra en un bote salvavidas con un único superviviente, un tigre de bengala con quien labrará una emocionante, increíble e inesperada relación.',
		'imagen' => 'life_of_pi.jpg','activo' => true, 'precio' => '120', 'categorias' => array (13,18)),
		26 => array( 'id' => '26',
		'nombre' => 'Cast Away', 
		'genero' => 'Aventura, Drama',
		'anio' => '2000',
		'director' => 'Robert Zemeckis', 
		'actores' => 'Tom Hanks, Helen Hunt, Nick Searcy',
		'duracion' => '2h 23 min', 
		'rating' => '7.2', 
		'clasificacion' => 'ATP',
		'descripcion' => 'Tras un naufragio en medio del océano Pacífico, el joven hindú Pi, hijo de un guarda de zoo que viajaba de la India a Canadá, se encuentra en un bote salvavidas con un único superviviente, un tigre de bengala con quien labrará una emocionante, increíble e inesperada relación.',
		'imagen' => 'cast_away.jpg','activo' => true, 'precio' => '100', 'categorias' => array (13,18)),
		27 => array( 'id' => '27',
		'nombre' => 'The Revenant', 
		'genero' => 'Aventura',
		'anio' => '2015',
		'director' => 'Alejandro González Iñárritu', 
		'actores' => 'Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson',
		'duracion' => '2h 36 min', 
		'rating' => '7.2', 
		'clasificacion' => '+16',
		'descripcion' => 'Año 1823. En las profundidades de la América salvaje, el explorador Hugh Glass (Leonardo DiCaprio) participa junto a su hijo mestizo Hawk en una expedición de tramperos que recolecta pieles. Glass resulta gravemente herido por el ataque de un oso y es abandonado a su suerte por un traicionero miembro de su equipo, John Fitzgerald (Tom Hardy). Con la fuerza de voluntad como su única arma, Glass deberá enfrentarse a un territorio hostil, a un invierno brutal y a la guerra constante entre las tribus de nativos americanos, en una búsqueda implacable para conseguir vengarse.',
		'imagen' => 'the_revenant.jpg','activo' => true, 'precio' => '150', 'categorias' => array (13)),
		28 => array( 'id' => '28',
		'nombre' => 'Monsters, Inc.', 
		'genero' => 'Infantil, Comedia',
		'anio' => '2001',
		'director' => 'Peter Docter', 
		'actores' => 'Billy Crystal, John Goodman, Mary Gibbs',
		'duracion' => '1h 38 min', 
		'rating' => '7.6', 
		'clasificacion' => 'ATP',
		'descripcion' => 'Monsters Inc. es la mayor empresa de miedo del mundo, y James P. Sullivan es uno de sus mejores empleados. Asustar a los niños no es un trabajo fácil, ya que todos creen que los niños son tóxicos y no pueden tener contacto con ellos. Pero un día una niña se cuela sin querer en la empresa, provocando el caos.',
		'imagen' => 'monsters_inc.jpg','activo' => true, 'precio' => '100', 'categorias' => array (15,20)),
		29 => array( 'id' => '29',
		'nombre' => 'Cars', 
		'genero' => 'Infantil, Aventura, Comedia',
		'anio' => '2006',
		'director' => 'John Lasseter', 
		'actores' => 'Owen Wilson, Bonnie Hunt, Paul Newman',
		'duracion' => '1h 54 min', 
		'rating' => '6.2', 
		'clasificacion' => 'ATP',
		'descripcion' => 'El aspirante a campeón de carreras Rayo McQueen parece que está a punto de conseguir el éxito, la fama y todo lo que había soñado, hasta que por error toma un desvío inesperado en la polvorienta y solitaria Ruta 66. Su actitud arrogante se desvanece cuando llega a una pequeña comunidad olvidada que le enseña las cosas importantes de la vida que había olvidado.',
		'imagen' => 'cars.jpg','activo' => true, 'precio' => '100', 'categorias' => array (13,15,20)),
		30 => array( 'id' => '30',
		'nombre' => 'Toy Story', 
		'genero' => 'Infantil, Comedia',
		'anio' => '1995',
		'director' => 'John Lasseter', 
		'actores' => 'Tom Hanks, Tim Allen, Don Rickles',
		'duracion' => '1h 20 min', 
		'rating' => '7.7', 
		'clasificacion' => 'ATP',
		'descripcion' => 'Los juguetes de Andy, un niño de 6 años, temen que haya llegado su hora y que un nuevo regalo de cumpleaños les sustituya en el corazón de su dueño. Woody, un vaquero que ha sido hasta ahora el juguete favorito de Andy, trata de tranquilizarlos hasta que aparece Buzz Lightyear, un héroe espacial dotado de todo tipo de avances tecnológicos. Woody es relegado a un segundo plano. Su constante rivalidad se transformará en una gran amistad cuando ambos se pierden en la ciudad sin saber cómo volver a casa.',
		'imagen' => 'toy_story.jpg','activo' => true, 'precio' => '100', 'categorias' => array (15,20)),
		31 => array( 'id' => '31',
		'nombre' => 'Ice Age', 
		'genero' => 'Aventuras, Comedia, Infantil',
		'anio' => '2002',
		'director' => 'Chris Wedge', 
		'actores' => 'MDenis Leary, John Leguizamo, Ray Romano',
		'duracion' => '1h 15 min', 
		'rating' => '7.3', 
		'clasificacion' => 'ATP',
		'descripcion' => 'En la epoca glacial de la prehistoria un mamut, un perezoso gigante y un tigre se ocuparán de cuidar un bebé humano extraviado por su familia.',
		'imagen' => 'ice_age.jpg','activo' => true, 'precio' => '100', 'categorias' => array (13,15,20)),
		32 => array( 'id' => '32',
		'nombre' => 'Shrek', 
		'genero' => 'Aventuras, Comedia, Infantil',
		'anio' => '2001',
		'director' => 'Andrew Adamson', 
		'actores' => 'Mike Myers, Eddie Murphy, Cameron Diaz',
		'duracion' => '1h 27 min', 
		'rating' => '7.7', 
		'clasificacion' => 'ATP',
		'descripcion' => 'Hace mucho tiempo, en una lejanísima ciénaga, vivía un feroz ogro llamado Shrek. De repente, un día, su soledad se ve interrumpida por una invasión de sorprendentes personajes. Hay ratoncitos ciegos en su comida, un enorme y malísimo lobo en su cama, tres cerditos sin hogar y otros seres que han sido deportados de su tierra por el malvado Lord Farquaad. Para salvar su territorio, Shrek hace un pacto con Farquaad y emprende viaje para conseguir que la bella princesa Fiona acceda a ser la novia del Lord. En tan importante misión le acompaña un divertido burro, dispuesto a hacer cualquier cosa por Shrek: todo, menos guardar silencio.',
		'imagen' => 'shrek.jpg','activo' => true, 'precio' => '100', 'categorias' => array (13,15,20)),
		33 => array( 'id' => '33',
		'nombre' => 'Asesino Solitario', 
		'genero' => 'Accion, Suspenso',
		'anio' => '2007',
		'director' => 'Philip Atwell', 
		'actores' => 'Jet Li, Jason Statham, John Lone, Devon Aoki, Luis Guzmán, Saul Rubinek, Ryo Ishibashi, Sung Kang, Nadine Velazquez, Kane Kosugi',
		'duracion' => '1h 31min', 'rating' => '9.2', 'clasificacion' => '+18',
		'descripcion' => 'Después de que su compañero Tom Lone y su familia son asesinados aparentemente por el infame y esquivo asesino Rogue, el agente del FBI John Crawford se obsesiona con la venganza mientras su mundo se desmorona en un torbellino de culpa y traición. Rogue finalmente resurge para resolver su propia cuenta, desencadenando una sangrienta guerra criminal entre los rivales de la mafia asiática Chang of the Triad y el jefe de Yakuza, Shiro. Cuando Jack y Rogue finalmente se encuentren cara a cara, se revelará la verdad última de sus pasados.',
		'imagen' => 'asesino_solitario.jpg','activo' => true, 'precio' => '120', 'categorias' => array(12,23)),
		34 => array( 'id' => '34',
		'nombre' => 'Bala Perdida', 
		'genero' => 'Accion, Suspenso, Crimen',
		'anio' => '2020',
		'director' => 'Guillaume Pierret', 
		'actores' => 'Nicolas Duvauchelle, Ramzy Bedia, Alban Lenoir, Stéfi Celma',
		'duracion' => '1h 32min', 'rating' => '9.2', 'clasificacion' => '+18',
		'descripcion' => 'Lino (Alban Lenoir), un mecánico con un don especial para construir coches, ingresa en prisión por un robo que salió mal. Sin embargo, el jefe de una unidad especial de lucha contra las drogas le ofrece un trato para evitar la cárcel: ser mecánico de la policía. Nueve meses más tarde, Lino, que ha demostrado su valía y su reconstrucción personal, es acusado injustamente de asesinato. Ahora, la única prueba que puede demostrar su inocencia es encontrar la bala del crimen alojada en un coche desaparecido.',
		'imagen' => 'balaperdida.jpg','activo' => true, 'precio' => '120', 'categorias' => array(12,16,23)),
		35 => array( 'id' => '35',
		'nombre' => 'Capitana Marvel', 
		'genero' => 'Accion, Suspenso, Ciencia y Ficcion, Fantasia',
		'anio' => '2019',
		'director' => 'Anna Boden, Ryan Fleck', 
		'actores' => 'Brie Larson, Samuel L. Jackson, Jude Law',
		'duracion' => '2h 40min', 'rating' => '9.2', 'clasificacion' => 'ATP',
		'descripcion' => 'Ubicada en los 90. "Capitana Marvel" es una nueva aventura que nos presentará un periodo de la historia nunca antes vista en el MCU, que seguirá el viaje de Carol Danvers para convertirse en una de las heroínas más poderosas del universo. Mientras una guerra galáctica entre dos razas alienígenas llega a la Tierra, Danvers se encuentra a sí misma y a un pequeño grupo de aliados, en el centro del remolino.',
		'imagen' => 'capitana_marvel.jpg','activo' => true, 'precio' => '150', 'categorias' => array(12,14,19,23)),
		36 => array( 'id' => '36',
		'nombre' => 'Despertares', 
		'genero' => 'Drama',
		'anio' => '1990',
		'director' => 'Penny Marshall', 
		'actores' => 'Robert De Niro, Robin Williams, John Heard, Penelope Ann Miller',
		'duracion' => '2h 1min', 'rating' => '9.2', 'clasificacion' => '+13',
		'descripcion' => 'El médico Malcolm Sayer, se encuentra con una sala llena de catatónicos víctimas de una epidemia de encefalitis. El doctor se perturba ante esta situación y por el hecho de que muchos son catatónicos desde hace décadas sin esperanza de cualquier cura. Sayer investiga para dar con alguna solución y encuentra una posible cura química y prueba con uno de ellos, Leonard Lowe. Ahora él es adulto después de haber entrado en un estado catatónico en su adolescencia.',
		'imagen' => 'despertares.jpg','activo' => true, 'precio' => '120', 'categorias' => array(18)),
		37 => array( 'id' => '37',
		'nombre' => 'Hombre de Familia', 
		'genero' => 'Drama, Ciencia y Ficcion, Romance, Fantasia, Comedia',
		'anio' => '2000',
		'director' => 'Brett Ratner', 
		'actores' => 'Nicolas Cage, Téa Leoni, Don Cheadle, Amber Valletta',
		'duracion' => '2h 5min', 'rating' => '9.2', 'clasificacion' => '+13',
		'descripcion' => 'Jack Campbell (Nicolas Cage) es un egocéntrico broker de Wall Street cuya única obsesión es el trabajo y una vida llena de lujo. Un día, tras un incidente en una tienda durante la Nochebuena, se despierta viviendo otra vida alternativa: ahora es un humilde vendedor de neumáticos de Nueva Jersey, casado con su antigua novia Kate (Téa Leoni), a la que había abandonado hace años para no obstaculizar su carrera en el mundo de las finanzas.',
		'imagen' => 'hombre_de_familia.jpg','activo' => true, 'precio' => '130', 'categorias' => array(14,15,18,19,22)),
		38 => array( 'id' => '38',
		'nombre' => 'Siente el Ritmo', 
		'genero' => 'Drama, Musica, Comedia',
		'anio' => '2020',
		'director' => 'Elissa Down', 
		'actores' => 'Sofia Carson, Enrico Colantoni, Wolfgang Novogratz, Donna Lynne Champlin',
		'duracion' => '1h 49min', 'rating' => '9.2', 'clasificacion' => 'ATP',
		'descripcion' => 'Cuando la bailarina talentosa y egocéntrica April (Sofía Carson) es desterrada de Broadway, ella se muda a regañadientes con su padre (Enrico Colantoni) en su pequeña ciudad natal de Wisconsin. Haciendo todo lo posible para evitar a todos en su comunidad unida, incluido su primer amor Nick (Wolfgang Novogratz), April es reclutada a regañadientes por su antigua maestra de baile (Donna Lynne Champlin) para entrenar al grupo de jóvenes bailarines inadaptados de la ciudad. Inicialmente creyendo que ha encontrado el camino de regreso a Broadway, April gana mucho más. Una carta de amor a los pueblos.',
		'imagen' => 'siente_el_ritmo.jpg','activo' => true, 'precio' => '120', 'categorias' => array(15,18,21)),
		39 => array( 'id' => '39',
		'nombre' => 'El poder del Tai chi', 
		'genero' => 'Accion, Artes Marcials, Aventura, Drama',
		'anio' => '2013',
		'director' => 'Elissa Down', 
		'actores' => 'Tiger Hu Chen, Keanu Reeves, Karen Mok, Simon Yam',
		'duracion' => '1h 45min', 'rating' => '9.2', 'clasificacion' => '+16',
		'descripcion' => 'Chen (Reeves) es un joven con experiencia y un don innato para el combate. Será en el Pekín actual donde todo su potencial se vea desarrollado y explotado, abriendo ante él un infinito abanico de posibilidades. La grandeza como hombre y los sacrificios como persona le acompañarán en un viaje para descubrirse a sí mismo a través del cuerpo a cuerpo. Un trepidante viaje cargado de acción en una revolucionaria visión sobre las peleas de artes marciales, una exquisita mezcla de fuerza y agilidad de movimientos desde una perspectiva privilegiada con las nuevas tecnologías. Una batalla personal que se debatirá a base de dolor y sangre.',
		'imagen' => 'el_poder_del_taichi.jpg','activo' => true, 'precio' => '130', 'categorias' => array(12,13,18)),
		40 => array( 'id' => '40',
		'nombre' => 'En el nombre Hombre del Rey', 
		'genero' => 'Drama, Aventura , Fantasía, Ciencia Ficción, Acción, Horror, Thriller, Guerra',
		'anio' => '2008',
		'director' => 'Uwe Boll', 
		'actores' => 'Jason Statham, John Rhys-Davies, Ray Liotta, Leelee Sobieski',
		'duracion' => '2h 4min', 'rating' => '9.2', 'clasificacion' => '+16',
		'descripcion' => 'Ambientada en el reino de Ehb, la historia sigue a Farmer, quien fue adoptado por su pueblo. Cuando la esposa de Farmer, Solana, y su hijo se van a vender verduras a Stonebridge, la granja de Farmer es atacada por criaturas llamadas Krugs. Con la ayuda de su amigo y vecino Norrick, viaja a Stonebridge donde están su esposa y su hijo. Antes de llegar, los Krugs, controlados por el mago Gallian, matan a su hijo y capturan a su esposa. Farmer, con la ayuda de Bastian , su cuñado, y Norrick se disponen a buscar y rescatar a su esposa. El sobrino del rey Barbecho está conspirando con el mago Gallian para hacerse cargo del reino dirigido por el rey Konreid.',
		'imagen' => 'el_hombre_del_rey.jpg','activo' => true, 'precio' => '130', 'categorias' => array(12,13,14,19,23,24)),
		41 => array( 'id' => '41',
		'nombre' => 'Vecinos en la mira', 
		'genero' => 'Suspenso, Drama, Crimen, Thriller, Misterio',
		'anio' => '2008',
		'director' => 'Neil LaBute', 
		'actores' => 'Samuel L. Jackson, Patrick Wilson, Kerry Washington, Justin Chambers',
		'duracion' => '1h 50min', 'rating' => '9.2', 'clasificacion' => '+16',
		'descripcion' => 'Una joven pareja (Patrick Wilson y Kerry Washington) se acaba de mudar a la casa de sus sueños en California. Muy pronto descubrirán que no son bien recibidos por uno de sus vecinos (Samuel L. Jackson), un severo padre soltero, oficial de la policía de Los Ángeles estrechamente unido al cuerpo, que se ha designado a sí mismo como guardián del vecindario. Sin motivo especial, el policía empezará a acosarlos.',
		'imagen' => 'vecinos_en_la_mira.jpg','activo' => true, 'precio' => '130', 'categorias' => array(16,18,23,24)),
		42 => array( 'id' => '42',
		'nombre' => 'Codigo del Miedo', 
		'genero' => 'Crimen, Acción, Suspenso, Thriller',
		'anio' => '2012',
		'director' => 'Boaz Yakin', 
		'actores' => 'Jason Statham, Chris Sarandon, Robert John Burke, Catherine Chan',
		'duracion' => '1h 50min', 'rating' => '9.2', 'clasificacion' => '+16',
		'descripcion' => 'Luke Wright (Jason Statham, Los mercenarios) se ha metido en un grave problema con las mafias rusas. Después de haber perdido un combate amañado, los miembros del clan han asesinado a su esposa y lo han condenado a vivir en un exilio social permanente: cualquier persona con la que se relacione, tendrá el mismo destino que su mujer. Desesperado, Luke intentará crear a su alrededor una nueva vida, pero le será imposible, por lo que se convertirá en un vagabundo errático y miserable perdido por las calles neoyorkinas.',
		'imagen' => 'codigodel_miedo.jpg','activo' => true, 'precio' => '130', 'categorias' => array(12,16,23,24)),
		43 => array( 'id' => '43',
		'nombre' => 'El Redentor', 
		'genero' => 'Drama, Suspenso, Acción, Thriller',
		'anio' => '2013',
		'director' => 'Steven Knight', 
		'actores' => 'Jason Statham, Benedict Wong, Agata Buzek, Vicky McClure',
		'duracion' => '1h 40min', 'rating' => '9.2', 'clasificacion' => '+16',
		'descripcion' => 'Joey Jones (Jason Statham) es un ex soldado de las Fuerzas Especiales, vagabundo y atormentado por un trágico pasado. Harto de las injusticias que ve constantemente a su alrededor, los acontecimientos le llevan a convertirle en un “ángel vengador”. Pronto verá como su pasado se mezcla con su turbio presente y cómo sus intentos de forjar una nueva vida comienzan a desmontarse.',
		'imagen' => 'el_redentor.jpg','activo' => true, 'precio' => '130', 'categorias' => array(12,18,23,24)),
		44 => array( 'id' => '44',
		'nombre' => 'Titanes del Pacifico: La Insurreccion', 
		'genero' => 'Ciencia Ficción, Acción',
		'anio' => '2018',
		'director' => 'Steven S. DeKnight', 
		'actores' => 'John Boyega, Scott Eastwood, Jing Tian',
		'duracion' => '2h 20min', 'rating' => '9.2', 'clasificacion' => '+13',
		'descripcion' => 'Un futuro cercano. Han pasado 10 años tras la primera invasión que sufrió la humanidad, pero la lucha aún no ha terminado. El planeta vuelve a ser asediado por los Kaiju, una raza de alienígenas colosales, que emergen desde un portal interdimensional con el objetivo de destruir a la raza humana. Ante esta nueva amenaza, los Jaegers, robots gigantes de guerra pilotados por dos personas para sobrellevar la inmensa carga neuronal que conlleva manipularlos, ya no están a la altura de lo que se les viene encima. Será entonces cuando los supervivientes de la primera invasión, además de nuevos personajes como el hijo de Pentecost (John Boyega), tendrán que idear la manera de sorprender al enorme enemigo, apostando por nuevas estrategias defensivas y de ataque. Con la Tierra en ruinas e intentando reconstruirse, esta nueva batalla puede ser decisiva para el futuro. También conocido con el nombre de "Pacific Rim: Insurrección".',
		'imagen' => 'pacific_rim.jpg','activo' => true, 'precio' => '140', 'categorias' => array(12,14)),
		45 => array( 'id' => '45',
		'nombre' => 'The Driver', 
		'genero' => 'Acción, Horror',
		'anio' => '2019',
		'director' => 'Wych Kaosayananda', 
		'actores' => 'Mark Dacascos, Jeremy Stutes, Julie Condra, Noelani Dacascos',
		'duracion' => '1h 37min', 'rating' => '9.2', 'clasificacion' => '+16',
		'descripcion' => 'Después de que una plaga de muertos vivientes diezme la vida humana en la tierra, un ex asesino a sueldo (Mark Dacascos), su esposa (Julie Condra) y su hija, Bree (Noelani Dacascos) , vive tranquilamente en un complejo de supervivencia. Pero cuando su base es atacada, una explosión masiva convoca a un enjambre de muertos vivientes. Escapan y deben buscar el refugio, un rumoreado santuario al norte, mientras el padre le enseña a su hija a disparar, conducir y sobrevivir antes de que se agote el tiempo.',
		'imagen' => 'the_driver.jpg','activo' => true, 'precio' => '130', 'categorias' => array(12,24)),
		
		//Sebastian Tolaba
		// Categoria principal: Musical
		46 => array( 'id' => '46',
		'nombre' => 'High School Musical', 
		'genero' => 'Musical, Comedia, Familiar', 
		'anio' => '2006',
		'director' => 'Kenny Ortega', 
		'actores' => 'Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lucas Grabeel, Corbin Bleu, Monique Coleman',
		'duracion' => '98 min.', 
		'rating' => '5.4', 'clasificacion' => 'ATP',
		'descripcion' => 'Un popular atleta de secundaria y una chica académicamente talentosa obtienen papeles en el musical de la escuela y desarrollan una amistad que amenaza el orden social de East High.',
		'imagen' => 'high_school_musical.jpg','activo' => true, 'precio' => '100', 'categorias' => array (21,15)),
		
		47 => array( 'id' => '47',
		'nombre' => 'High School Musical 2', 
		'genero' => 'Musical, Comedia, Familiar', 
		'anio' => '2007',
		'director' => 'Kenny Ortega', 
		'actores' => 'Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lucas Grabeel, Corbin Bleu,Monique Coleman',
		'duracion' => '106 min.', 
		'rating' => '5.0', 
		'clasificacion' => 'ATP',
		'descripcion' => 'La escuela terminó por verano y los East High Wildcats están listos para convertirlo en el momento de sus vidas después de conseguir trabajos en un club de campo adinerado propiedad de la familia de Sharpay y Ryan.',
		'imagen' => 'high_school_musical_2.jpg','activo' => true, 'precio' => '100', 'categorias' => array(21,15)),
		
		48 => array( 'id' => '48',
		'nombre' => 'Bohemian Rhapsody', 
		'genero' => 'musical',
		'anio' => '2018',
		'director' => 'Bryan Singer', 
		'actores' => 'Rami Malek, Gwilym Lee, Ben Hardy, Joseph Mazzello',
		'duracion' => '134 min.', 
		'rating' => '8.0', 
		'clasificacion' => '+13',
		'descripcion' => 'La historia de la legendaria banda de rock británica Queen y el cantante principal Freddie Mercury , antes de su famosa actuación en Live Aid (1985).',
		'imagen' => 'bohemian_rhapsody.jpg','activo' => true, 'precio' => '120', 'categorias' => array (18,21)),
		
		49 => array( 'id' => '49',
		'nombre' => 'Gilda, no me arrepiento de este amor', 
		'genero' => 'Musical, Drama',
		'anio' => '2016',
		'director' => 'Lorena Muñoz', 
		'actores' => 'Natalia Oreiro, Ángela Torres, Javier Drolas, Lautaro Delgado, Roly Serrano, Susana Pampín, Marcelo Melingo',
		'duracion' => '118 min.', 
		'rating' => '6.9', 
		'clasificacion' => '+13',
		'descripcion' => 'Gilda, la artista, que comenzó su carrera respondiendo a un anuncio, hubo de sobreponerse al rechazo inicial de su familia, pero su voz y su carisma le ganaron un lugar en el estrellato, mitificándose su figura después de fallecer a los 34 años',
		'imagen' => 'gilda.jpg','activo' => true, 'precio' => '120', 'categorias' => array(21,18)),
		
		50 => array( 'id' => '50',
		'nombre' => 'Escuela de rock', 
		'genero' => 'Musical, Comedia',
		'anio' => '2003',
		'director' => 'Richard Linklater', 
		'actores' => 'Jack Black, Joan Cusack, Sarah Silverman, Mike White, Miranda Cosgrove, Kevin Clark, Joey Gaydos Jr.',
		'duracion' => '109 min.', 
		'rating' => '7.1', 
		'clasificacion' => 'ATP',
		'descripcion' => 'Después de ser expulsado de su banda de rock, Dewey Finn se convierte en maestro sustituto de una escuela primaria privada, solo para intentar convertir su clase en una banda de rock.',
		'imagen' => 'escuela_de_rock.jpg','activo' => true, 'precio' => '100', 'categorias' => array (21,15)),
		//Final Categoria Musical

		//Categoria Principal: Romance
		51 => array( 'id' => '51',
		'nombre' => '3 metros sobre el cielo', 
		'genero' => 'Romance, Drama, Accion', 
		'anio' => '2010',
		'director' => 'Fernando González Molina', 
		'actores' => 'Mario Casas, Maria Valverde, Álvaro Cervantes, Marina Salas, Andrea Duro, Nerea Camacho, Luis Fernández, Diego Martín',
		'duracion' => '119 min.', 
		'rating' => '7.0', 
		'clasificacion' => '+13',
		'descripcion' => 'Una mujer privilegiada y un hombre temerario se enamoran a pesar de sus diferentes clases sociales.',
		'imagen' => '3msc.jpg','activo' => true, 'precio' => '120', 'categorias' => array(22,18,12)),
		
		52 => array( 'id' => '52',
		'nombre' => 'Tengo ganas de ti', 
		'genero' => 'Romance, Drama',
		'anio' => '2012',
		'director' => 'Fernando González Molina', 
		'actores' => 'Mario Casas, Clara Lago, María Valverde, Nerea Camacho, Luis Fernández, Diego Martín, Álvaro Cervantes, Marina Salas, Antonio Velázquez, Carme Elías, Víctor Sevilla',
		'duracion' => '2h', 
		'rating' => '6.9', 
		'clasificacion' => '+13',
		'descripcion' => 'La secuela de 3 Metros Sobre El Cielo, comienza con el regreso de H a su ciudad natal, donde volver a conectar con el pasado significa lucha y también un nuevo amor.',
		'imagen' => 'tengo_ganas_de_ti.jpg','activo' => true, 'precio' => '120', 'categorias' => array (22,18)),
		
		53 => array( 'id' => '53',
		'nombre' => 'Grease', 
		'genero' => 'Romance, Musical',
		'anio' => '1978',
		'director' => 'Randal Kleiser', 
		'actores' => 'John Travolta, Olivia Newton-John, Stockard Channing, Jeff Conaway',
		'duracion' => '110 min.', 
		'rating' => '7.2', 
		'clasificacion' => '+13',
		'descripcion' => 'La buena chica Sandy Olsson y el engrasador Danny Zuko se enamoraron durante el verano. Cuando descubran inesperadamente que ahora están en la misma escuela secundaria, ¿podrán reavivar su romance?',
		'imagen' => 'grease.jpg','activo' => true, 'precio' => '120', 'categorias' => array (22,21)),
		
		54 => array( 'id' => '54',
		'nombre' => 'Como si fuera la primera vez', 
		'genero' => 'Romance, Drama, Comedia',
		'anio' => '2004',
		'director' => 'Peter Segal', 
		'actores' => 'Adam Sandler, Drew Barrymore, Rob Schneider, Sean Astin',
		'duracion' => '99 min.', 
		'rating' => '6.8', 
		'clasificacion' => '+13',
		'descripcion' => 'Henry Roth es un hombre que le teme al compromiso hasta que conoce a la hermosa Lucy. Se llevan bien y Henry piensa que finalmente ha encontrado a la chica de sus sueños hasta que descubre que tiene pérdida de memoria a corto plazo y lo olvida al día siguiente.',
		'imagen' => 'como_si_fuera_la_primera_vez.jpg','activo' => true, 'precio' => '120', 'categorias' => array (22,18,15)),
		
		55 => array( 'id' => '55',
		'nombre' => 'Titanic', 
		'genero' => 'Romance, Drama',
		'anio' => '1997',
		'director' => 'James Cameron', 
		'actores' => 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Gloria Stuart, Bill Paxton, Kathy Bates, Frances Fisher, Victor Garber, Bernard Hill, Jonathan Hyde, David Warner, Bernard Fox, Danny Nucci, Ioan Gruffudd',
		'duracion' => '195 min', 
		'rating' => '7.8', 
		'clasificacion' => '+13',
		'descripcion' => 'Un aristócrata de diecisiete años se enamora de un artista amable pero pobre a bordo del lujoso y desafortunado RMS Titanic.',
		'imagen' => 'titanic.jpg','activo' => true, 'precio' => '120', 'categorias' => array (22,18)),
		// Final Romance

		// Categoria Principal: Crimen		
		56 => array( 'id' => '56',
		'nombre' => 'Joker ', 
		'genero' => 'Crimen, Drama, Suspenso',
		'anio' => '2019',
		'director' => 'Todd Phillips', 
		'actores' => 'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen, Glenn Fleshler, Bill Camp, Shea Whigham, Marc Maron',
		'duracion' => '122 min.', 
		'rating' => '8.5', 
		'clasificacion' => '+16',
		'descripcion' => 'En Gotham City, el comediante con problemas mentales Arthur Fleck es ignorado y maltratado por la sociedad. Luego se embarca en una espiral descendente de revolución y crímenes sangrientos. Este camino lo pone cara a cara con su alter ego: el Joker.',
		'imagen' => 'joker.jpg','activo' => true, 'precio' => '150', 'categorias' => array (16,18,23)),
		
		57 => array( 'id' => '57',
		'nombre' => 'El lobo de Wall Street', 
		'genero' => 'Crimen, Drama',
		'anio' => '2013',
		'director' => 'Martin Scorsese', 
		'actores' => 'Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey, Kyle Chandler, Rob Reiner, Jon Favreau, Jean Dujardin, Jon Bernthal',
		'duracion' => '180 min.', 
		'rating' => '8.2', 
		'clasificacion' => '+16',
		'descripcion' => 'Basado en la historia real de Jordan Belfort , desde su ascenso a un adinerado corredor de bolsa que vive la buena vida hasta su caída que involucra el crimen, la corrupción y el gobierno federal.',
		'imagen' => 'el_lobo_de_wall_street.jpg','activo' => true, 'precio' => '150', 'categorias' => array (16,18)),
		
		58 => array( 'id' => '58',
		'nombre' => 'No respires', 
		'genero' => 'Crimen, Terror, Suspenso',
		'anio' => '2016',
		'director' => 'Fede Alvarez', 
		'actores' => 'Jane Levy, Dylan Minnette, Daniel Zovatto, Stephen Lang',
		'duracion' => '88 min.', 
		'rating' => '7.1', 
		'clasificacion' => '+16',
		'descripcion' => 'Con la esperanza de marcharse con una enorme fortuna, un trío de ladrones irrumpe en la casa de un ciego que no es tan indefenso como parece.',
		'imagen' => 'no_respires.jpg','activo' => true, 'precio' => '150', 'categorias' => array (16,24,23)),
		
		59 => array( 'id' => '59',
		'nombre' => 'La masacre de Texas: El origen de Leatherface', 
		'genero' => 'Crimen, Terror, Suspenso',
		'anio' => '2017',
		'director' => 'Alexandre Bustillo, Julien Maury', 
		'actores' => 'Lili Taylor, Stephen Dorff, Sam Strike, Vanessa Grasse',
		'duracion' => '90 min', 
		'rating' => '5.0', 
		'clasificacion' => '+18',
		'descripcion' => 'Leatherface adolescente escapa de un hospital psiquiátrico con otros tres reclusos, secuestra a una joven enfermera y la lleva a un viaje por carretera desde el infierno, mientras es perseguida por un agente de la ley en busca de venganza.',
		'imagen' => 'leatherface.jpg','activo' => true, 'precio' => '200', 'categorias' => array (16,24,23)),
		
		60 => array( 'id' => '60',
		'nombre' => 'Ciudad de Dios', 
		'genero' => 'Crimen, Drama',
		'anio' => '2002',
		'director' => 'Fernando Meirelles, Kátia Lund', 
		'actores' => 'Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva, Jonathan Haagensen, Matheus Nachtergaele, Seu Jorge',
		'duracion' => '130 min.', 
		'rating' => '8.6', 
		'clasificacion' => '+16',
		'descripcion' => 'En los barrios marginales de Río, los caminos de dos niños divergen mientras uno lucha por convertirse en fotógrafo y el otro en capo.',
		'imagen' => 'ciudad_de_dios.jpg','activo' => true, 'precio' => '150', 'categorias' => array (16,18)),
		// Final Crimen
		
		// Categoria Principal: Documental
		61 => array( 'id' => '61',
		'nombre' => 'I Am not Your Negro', 
		'genero' => 'Documental',
		'anio' => '2016',
		'director' => 'Raoul Peck', 
		'actores' => 'Samuel L. Jackson, Harry Belafonte, Marlon Brando, George W. Bush, Ray Charles, Gary Cooper, Joan Crawford, Tony Curtis, Doris Day, Bob Dylan, Audrey Hepburn, Charlton Heston, Robert F. Kennedy, Joseph L. Mankiewicz, Barack Obama, Michelle Obama, Sidney Poitier, Arnold Schwarzenegger, Rod Steiger, John Wayne, Richard Widmark, Billy Dee Williams, Fay Wray',
		'duracion' => '95 min.', 
		'rating' => '7.9', 
		'clasificacion' => '+13',
		'descripcion' => 'El escritor James Baldwin realizó en 1979 un ensayo, Remember This House, sobre el racismo en Estados Unidos, hablando de su relación con Malcolm X, Martin Luther King, Medgar Evers, entre otros activistas, y el proceso por la lucha de los derechos de los afroestadounidenses.2​',
		'imagen' => 'i_am_not_your_negro.jpg','activo' => true, 'precio' => '120', 'categorias' => array (17)),
		
		62 => array( 'id' => '62',
		'nombre' => 'Capturing the Friedmans', 
		'genero' => 'Documental',
		'anio' => '2003',
		'director' => 'Andrew Jarecki', 
		'actores' => 'Arnold Friedman, Elaine Friedman, David Friedman, Seth Friedman, Jesse Friedman',
		'duracion' => '107 min.', 
		'rating' => '7.7', 
		'clasificacion' => '+16',
		'descripcion' => 'Documental sobre los Friedman, una familia judía aparentemente típica de clase media alta cuyo mundo se transforma instantáneamente cuando el padre y su hijo menor son arrestados y acusados ​​de crímenes espantosos y horribles.',
		'imagen' => 'capturing_the_friedmans.jpg','activo' => true, 'precio' => '150', 'categorias' => array (17)),
		
		63 => array( 'id' => '63',
		'nombre' => 'Líbranos del mal', 
		'genero' => 'Documental',
		'anio' => '2006',
		'director' => 'Amy Berg', 
		'actores' => "Oliver O'Grady",
		'duracion' => '101 min.', 
		'rating' => '7.9', 
		'clasificacion' => '+16',
		'descripcion' => "Documental sobre el padre Oliver O'Grady , un sacerdote católico que fue reubicado en varias parroquias de los Estados Unidos durante la década de 1970 en un intento de la Iglesia Católica de encubrir la violación de decenas de niños.",
		'imagen' => 'libranos_del_mal.jpg','activo' => true, 'precio' => '150', 'categorias' => array (17)),
		
		64 => array( 'id' => '64',
		'nombre' => 'The Cove', 
		'genero' => 'Documental',
		'anio' => '2009',
		'director' => 'Louie Psihoyos', 
		'actores' => "Ric O'Barry, Hayden Panettiere, Isabel Lucas, Mandy-Rae Cruickshank, Paul Watson, Scott Baker, Louie Psihoyos",
		'duracion' => '90 min.', 
		'rating' => '8.4', 
		'clasificacion' => '+13',
		'descripcion' => "Utilizando equipos de última generación, un grupo de activistas, dirigido por el renombrado entrenador de delfines Ric O'Barry, se infiltra en una cala cerca de Taijii, Japón, para exponer un caso impactante de abuso animal y una seria amenaza para la salud humana.",
		'imagen' => 'the_cove.jpg','activo' => true, 'precio' => '120', 'categorias' => array (17)),
		
		65 => array( 'id' => '65',
		'nombre' => 'Life Itself', 
		'genero' => 'Documental',
		'anio' => '2014',
		'director' => 'Steve James', 
		'actores' => 'Roger Ebert, Chaz Ebert, Werner Herzog, A.O. Scott, Errol Morris, Ava DuVernay, Martin Scorsese, Stephen Stanton',
		'duracion' => '121 min', 
		'rating' => '7.8', 
		'clasificacion' => '+16',
		'descripcion' => 'La vida y carrera del reconocido crítico de cine y comentarista social Roger Ebert.',
		'imagen' => 'life_Itself.jpg','activo' => true, 'precio' => '150', 'categorias' => array (17)),
		66 => array( 'id' => '66',
		'nombre' => 'The Shawshank Redemption', 
		'genero' => 'Drama',
		'anio' => '1995',
		'director' => 'Frank Darabont', 
		'actores' => ' Tim Robbins, Morgan Freeman, Bob Gunton ',
		'duracion' => '2h 22min', 
		'rating' => '9.3', 
		'clasificacion' => '+16',
		'descripcion' => 'Un hombre inocente es enviado a una corrupta penitenciaria de Maine en 1947 y sentenciado a dos cadenas perpetuas por un doble asesinato.',
		'imagen' => 'the_shawshank_redemption.jpg','activo' => true, 'precio' => '150', 'categorias' => array (18)),
		// Final Documental

    );
	// Ejemplo de array que guarda los datos de cada pelicula
	/*65(Numero de array) => array( 'id' => '65', ***************EJEMPLO****************
		'nombre' => '', 
		'genero' => '',
		'anio' => '',
		'director' => '', 
		'actores' => '',
		'duracion' => '', 
		'rating' => '', 
		'clasificacion' => '',
		'descripcion' => '',
		'imagen' => '(NOMBRE DE LA IMAGEN).jpg','activo' => true, 'precio' => '', 'categorias' => array (NUMERO/S DEPENDIENDO DE LA/S CATEGORIAS QUE TENGA)),*/

    ?>